import Footer from "./components/layout/Footer/Footer";
import Header from "./components/layout/Header/Header";
import "./globals.css";
import PluginsInitializer from "/app/components/clients/PluginsInitializer";
import "/public/css/style.css";

export const metadata = {
	title: "Wekomarce - Multipurpose eCommerce",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body>
				<PluginsInitializer />
				{/* Header here */}
				<Header />

				{children}

				{/* Footer here */}
				<Footer />
			</body>
		</html>
	);
}
